-- Autocommands (https://neovim.io/doc/user/autocmd.html)
-- vim.api.nvim_create_autocmd("BufEnter", {
--   pattern = { "*.json", "*.jsonc" },
--   -- enable wrap mode for json files only
--   command = "setlocal wrap",
-- })
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "cpp", "c", 'objc', 'objcpp' },
--   callback = function()
--     local ls = require('user.plug_configs.lsp_signature')
--     ls.setup()
--   end,
-- })
